import {
  AlertCircle,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  MousePointer2,
  Type,
  ListFilter,
  CheckSquare,
  Radio,
  SlidersHorizontal,
  MessageSquare,
  Info,
  TableIcon,
  ChevronRightSquare,
  MenuIcon,
  List,
  Search,
  FormInput,
  ToggleLeft,
  FoldVertical,
  Timer,
  Bell,
  GripVertical,
  Upload,
  Download,
  Calendar,
  type LucideIcon,
  ImageIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  // Updated component icons
  button: MousePointer2,
  textField: Type,
  dropdown: ListFilter,
  checkbox: CheckSquare,
  radio: Radio,
  slider: SlidersHorizontal,
  modal: MessageSquare,
  tooltip: Info,
  table: TableIcon,
  pagination: ChevronRightSquare,
  menu: MenuIcon,
  multiSelect: List,
  autocomplete: Search,
  carousel: ImageIcon,
  form: FormInput,
  toggle: ToggleLeft,
  accordion: FoldVertical,
  progress: Timer,
  toast: Bell,
  dragDrop: GripVertical,
  upload: Upload,
  download: Download,
  calendar: Calendar,
}
